Repository BAMWelDX/weldx, pull requests merged in 2020-10, with the labels that each got.

#145 add missing asdf schemas to documentation
  doc/asdf-schemas.rst
  doc/schemas/core.rst
  doc/schemas/equipment.rst
  doc/schemas/measurement.rst
  doc/schemas/process.rst
  doc/schemas/time.rst
Labels: ASDF, documentation

#148 only plot CSM arrows in a single direction
  weldx/transformations.py
Labels: no-changelog-entry-needed, transformations

#147 add pint wrapper to geo constructor classes
  CHANGELOG.md
  README.md
  doc/index.rst
  weldx/asdf/tags/weldx/core/iso_groove.py
  weldx/geometry.py
Labels: units

#151 150 fix nbsphinx args
  .github/pull_request_template.md
  doc/conf.py
  weldx/asdf/tags/weldx/core/iso_groove.py
Labels: no-changelog-entry-needed

#143 add base classes to init file
  weldx/__init__.py
  weldx/transformations.py
Labels: no-changelog-entry-needed

#152 add disclaimer.md and disable prev/next buttons in sphinx documentation
  doc/conf.py
  doc/disclaimer.md
  doc/index.rst
Labels: documentation, no-changelog-entry-needed

#142 Geometry tutorial
  CHANGELOG.md
  doc/nitpick_ignore
  doc/tutorials.rst
  tutorials/geometry_02_geometry.ipynb
  weldx/asdf/tags/weldx/core/iso_groove.py
  weldx/geometry.py
  weldx/transformations.py
Labels: documentation

#154 Sphinx updates
  doc/conf.py
Labels: documentation

#158 update documentation and example
  .typo-ci.yml
  README.md
  doc/disclaimer.md
  doc/index.rst
  doc/schemas/process.rst
  tutorials/welding_example_01_basics.ipynb
Labels: documentation

#125 23 xarray utility
  CHANGELOG.md
  doc/conf.py
  tests/test_utility.py
  weldx/transformations.py
  weldx/utility.py
Labels: xarray

#138 Developers documentation
  .typo-ci.yml
  doc/devdoc.rst
  doc/developers_doc/.gitignore
  doc/developers_doc/quantities.ipynb
  doc/developers_doc/time_data.md
  doc/developers_doc/xarray.md
  doc/index.rst
Labels: documentation, no-changelog-entry-needed

#173 add asdf docs and remove magic methods from class-template.rst
  doc/_templates/class-template.rst
  doc/api.rst
  doc/asdf-extension.rst
  doc/asdf-schemas.rst
  doc/conf.py
  doc/devdoc.rst
  doc/index.rst
  doc/schemas/core.rst
  doc/schemas/equipment.rst
  doc/schemas/measurement.rst
  doc/schemas/process.rst
  doc/schemas/time.rst
  doc/tutorials.rst
  weldx/asdf/utils.py
Labels: documentation

#175 add sphinx_autodoc_typehints and list (default) napoleon settings
  doc/conf.py
  environment.yml
Labels: documentation

#162 CSM Timedelta Update
  .deepsource.toml
  .typo-ci.yml
  CHANGELOG.md
  doc/conf.py
  doc/nitpick_ignore
  tests/asdf_tests/test_asdf_core.py
  tests/test_transformations.py
  tests/test_utility.py
  tutorials/geometry_02_geometry.ipynb
  tutorials/transformations_02_coordinate_system_manager.ipynb
  tutorials/welding_example_01_basics.ipynb
  tutorials/welding_example_02_weaving.ipynb
  weldx/asdf/schemas/weldx.bam.de/weldx/core/transformations/coordinate_system_hierarchy-1.0.0.yaml
  weldx/asdf/schemas/weldx.bam.de/weldx/core/transformations/coordinate_system_hierarchy_subsystem-1.0.0.yaml
  weldx/asdf/schemas/weldx.bam.de/weldx/core/transformations/local_coordinate_system-1.0.0.yaml
  weldx/asdf/tags/weldx/core/transformations/coordinate_system_hierarchy.py
  weldx/asdf/tags/weldx/core/transformations/local_coordinate_system.py
  weldx/asdf/utils.py
  weldx/core.py
  weldx/geometry.py
  weldx/transformations.py
  weldx/utility.py
Labels: transformations

#176 add optional syntax to wx_shape validation
  CHANGELOG.md
  doc/shape-validation.md
  tests/asdf_tests/test_asdf_validators.py
  weldx/asdf/schemas/weldx.bam.de/weldx/core/time_series-1.0.0.yaml
  weldx/asdf/schemas/weldx.bam.de/weldx/debug/test_shape_validator-1.0.0.yaml
  weldx/asdf/tags/weldx/debug/test_shape_validator.py
  weldx/asdf/tags/weldx/time/datetimeindex.py
  weldx/asdf/tags/weldx/time/timedeltaindex.py
  weldx/asdf/validators.py
Labels: validation

#179 Dataclass check decorator
  CHANGELOG.md
  weldx/asdf/tags/weldx/core/iso_groove.py
  weldx/utility.py
Labels: units

#182 clean notebooks
  .github/workflows/clean_notebooks.yml
  doc/developers_doc/faq.md
  doc/developers_doc/quantities.ipynb
  tutorials/GMAW_process.ipynb
  tutorials/geometry_01_profiles.ipynb
  tutorials/geometry_02_geometry.ipynb
  tutorials/groove_types_01.ipynb
  tutorials/measurement_example.ipynb
  tutorials/timeseries_01.ipynb
  tutorials/transformations_01_coordinate_systems.ipynb
  tutorials/transformations_02_coordinate_system_manager.ipynb
  tutorials/welding_example_01_basics.ipynb
  tutorials/welding_example_02_weaving.ipynb
Labels: documentation, no-changelog-entry-needed
