Repository BAMWelDX/weldx, pull requests merged in 2020-09, with the labels that each got.

#117 update docstrings
  weldx/asdf/tags/weldx/core/iso_groove.py
Labels: documentation

#116 update syntax in tutorial notebooks
  tutorials/GMAW_process.ipynb
  tutorials/groove_types_01.ipynb
  tutorials/measurement_example.ipynb
  tutorials/timeseries_01.ipynb
  tutorials/transformations_01_coordinate_systems.ipynb
  tutorials/transformations_02_coordinate_system_manager.ipynb
  tutorials/welding_example_01_basics.ipynb
  tutorials/welding_example_02_weaving.ipynb
Labels: documentation

#119 Notebook syntax updates
  tests/asdf_tests/test_asdf_groove.py
  tutorials/GMAW_process.ipynb
  tutorials/geometry_01_profiles.ipynb
  tutorials/groove_types_01.ipynb
  tutorials/measurement_example.ipynb
  tutorials/timeseries_01.ipynb
  tutorials/transformations_01_coordinate_systems.ipynb
  tutorials/transformations_02_coordinate_system_manager.ipynb
  tutorials/welding_example_01_basics.ipynb
  tutorials/welding_example_02_weaving.ipynb
  weldx/asdf/schemas/weldx.bam.de/weldx/measurement/data_transformation-1.0.0.yaml
  weldx/asdf/tags/weldx/core/iso_groove.py
Labels: documentation

#108 Enhance CSM
  .typo-ci.yml
  CHANGELOG.md
  environment.yml
  tests/asdf_tests/test_asdf_core.py
  tests/test_transformations.py
  tutorials/transformations_02_coordinate_system_manager.ipynb
  weldx/asdf/schemas/weldx.bam.de/weldx/core/transformations/coordinate_system_hierarchy-1.0.0.yaml
  weldx/asdf/schemas/weldx.bam.de/weldx/core/transformations/coordinate_system_hierarchy_subsystem-1.0.0.yaml
  weldx/asdf/tags/weldx/core/transformations/coordinate_system_hierarchy.py
  weldx/transformations.py
Labels: transformations

#124 RTD + nbsphinx + sphinx-asdf setup
  .deepsource.toml
  .github/workflows/docs.yml
  .gitignore
  .readthedocs.yml
  .typo-ci.yml
  CHANGELOG.md
  README.md
  doc/.gitignore
  doc/_static/WelDX_notext.ico
  doc/_static/WelDX_notext.svg
  doc/api.rst
  doc/asdf-extension.rst
  doc/asdf-schemas.rst
  doc/conf.py
  doc/index.rst
  doc/schemas/core.rst
  doc/schemas/time.rst
  doc/tutorials.rst
  doc/tutorials/.gitignore
  environment.yml
  setup.cfg
  weldx/asdf/schemas/weldx.bam.de/weldx/core/time_series-1.0.0.yaml
Labels: documentation

#126 61 lcs timedelta support
  .github/workflows/docs.yml
  .typo-ci.yml
  CHANGELOG.md
  tests/test_transformations.py
  tests/test_utility.py
  tests/test_visualization.py
  tutorials/timeseries_01.ipynb
  tutorials/transformations_01_coordinate_systems.ipynb
  tutorials/transformations_02_coordinate_system_manager.ipynb
  tutorials/welding_example_01_basics.ipynb
  tutorials/welding_example_02_weaving.ipynb
  weldx/asdf/schemas/weldx.bam.de/weldx/core/transformations/local_coordinate_system-1.0.0.yaml
  weldx/asdf/tags/weldx/core/transformations/local_coordinate_system.py
  weldx/transformations.py
  weldx/utility.py
  weldx/visualization.py
Labels: transformations

#137 ReadTheDocs Documentation
  .gitignore
  .typo-ci.yml
  CHANGELOG.md
  README.md
  conda.recipe/build_env.yml
  doc/.gitignore
  doc/_templates/class-template.rst
  doc/_templates/module-template.rst
  doc/api.rst
  doc/conf.py
  doc/index.rst
  doc/nitpick_ignore
  environment.yml
  weldx/core.py
  weldx/geometry.py
  weldx/transformations.py
  weldx/utility.py
Labels: documentation

#139 disable conda build and sphinx action on draft PR
  .github/workflows/conda_build.yml
  .github/workflows/docs.yml
Labels: CI, no-changelog-entry-needed
