Repository BAMWelDX/weldx, pull requests merged in 2020-11, with the labels that each got.

#180 use sphinx-asdf from weldx fork
  environment.yml
Labels: CI, documentation

#177 example implementation with removing default coordinates/orientation
  CHANGELOG.md
  weldx/asdf/schemas/weldx.bam.de/weldx/core/transformations/local_coordinate_system-1.0.0.yaml
  weldx/asdf/tags/weldx/core/transformations/local_coordinate_system.py
  weldx/transformations.py
Labels: ASDF

#186 Trigger binder build
  .github/workflows/trigger_binder_build.yml
Labels: CI, documentation, no-changelog-entry-needed

#188 update nbsphinx config and notebook lists
  doc/conf.py
  tutorials/GMAW_process.ipynb
  tutorials/geometry_01_profiles.ipynb
  tutorials/geometry_02_geometry.ipynb
  tutorials/groove_types_01.ipynb
  tutorials/measurement_example.ipynb
  tutorials/timeseries_01.ipynb
  tutorials/transformations_01_coordinate_systems.ipynb
  tutorials/transformations_02_coordinate_system_manager.ipynb
  tutorials/welding_example_01_basics.ipynb
  tutorials/welding_example_02_weaving.ipynb
Labels: documentation, no-changelog-entry-needed

#181 groove schema refactor
  CHANGELOG.md
  doc/api.rst
  doc/asdf-schemas.rst
  doc/conf.py
  doc/schemas/core.rst
  doc/schemas/groove.rst
  scripts/aws_run.py
  scripts/groove_load_script.py
  scripts/groove_save_script.py
  tests/asdf_tests/test_asdf_aws_schema.py
  tests/asdf_tests/test_asdf_gmaw_process.py
  tests/asdf_tests/test_asdf_groove.py
  tutorials/GMAW_process.ipynb
  tutorials/groove_types_01.ipynb
  tutorials/welding_example_01_basics.ipynb
  tutorials/welding_example_02_weaving.ipynb
  weldx/__init__.py
  weldx/asdf/__init__.py
  weldx/asdf/constants.py
  weldx/asdf/extension.py
  weldx/asdf/schemas/weldx.bam.de/weldx/aws/design/weld_details-1.0.0.yaml
  weldx/asdf/schemas/weldx.bam.de/weldx/core/iso_groove-1.0.0.yaml
  weldx/asdf/schemas/weldx.bam.de/weldx/groove/iso_9692_1_2013_12/DHUGroove-1.0.0.yaml
  weldx/asdf/schemas/weldx.bam.de/weldx/groove/iso_9692_1_2013_12/DHVGroove-1.0.0.yaml
  weldx/asdf/schemas/weldx.bam.de/weldx/groove/iso_9692_1_2013_12/DUGroove-1.0.0.yaml
  weldx/asdf/schemas/weldx.bam.de/weldx/groove/iso_9692_1_2013_12/DVGroove-1.0.0.yaml
  weldx/asdf/schemas/weldx.bam.de/weldx/groove/iso_9692_1_2013_12/FFGroove-1.0.0.yaml
  weldx/asdf/schemas/weldx.bam.de/weldx/groove/iso_9692_1_2013_12/HUGroove-1.0.0.yaml
  weldx/asdf/schemas/weldx.bam.de/weldx/groove/iso_9692_1_2013_12/HVGroove-1.0.0.yaml
  weldx/asdf/schemas/weldx.bam.de/weldx/groove/iso_9692_1_2013_12/IGroove-1.0.0.yaml
  weldx/asdf/schemas/weldx.bam.de/weldx/groove/iso_9692_1_2013_12/UGroove-1.0.0.yaml
  weldx/asdf/schemas/weldx.bam.de/weldx/groove/iso_9692_1_2013_12/UVGroove-1.0.0.yaml
  weldx/asdf/schemas/weldx.bam.de/weldx/groove/iso_9692_1_2013_12/VGroove-1.0.0.yaml
  weldx/asdf/schemas/weldx.bam.de/weldx/groove/iso_9692_1_2013_12/VVGroove-1.0.0.yaml
  weldx/asdf/schemas/weldx.bam.de/weldx/groove/terms-1.0.0.yaml
  weldx/asdf/tags/weldx/__init__.py
  weldx/asdf/tags/weldx/core/__init__.py
  weldx/asdf/tags/weldx/groove/__init__.py
  weldx/asdf/tags/weldx/groove/iso_9692_1.py
  weldx/asdf/tags/weldx/processes/__init__.py
  weldx/asdf/tags/weldx/processes/process.py
  weldx/welding/__init__.py
  weldx/welding/groove/__init__.py
  weldx/welding/groove/iso_9692_1.py
  weldx/welding/processes.py
Labels: ASDF

#195 update github action versions
  .github/workflows/conda_build.yml
  .github/workflows/docs.yml
  .github/workflows/pytest.yml
  .github/workflows/pytest_asdf.yml
  .github/workflows/static_analysis.yml
Labels: CI, no-changelog-entry-needed

#194 doc restructure and cleanup
  doc/asdf-extension.rst
  doc/asdf-schemas.rst
  doc/conf.py
  doc/devdoc.rst
  doc/developers_doc/.gitignore
  doc/developers_doc/faq.md
  doc/developers_doc/quantities.ipynb
  doc/developers_doc/time_data.md
  doc/developers_doc/xarray.md
  doc/index.rst
  doc/standard.rst
  doc/tutorials.rst
  tutorials/welding_example_01_basics.ipynb
Labels: documentation, no-changelog-entry-needed

#204 Update black formatting
  .git-blame-ignore-revs
  .github/workflows/static_analysis.yml
  tests/asdf_tests/test_asdf_core.py
  tests/asdf_tests/test_asdf_time.py
  tests/asdf_tests/test_asdf_validators.py
  tests/test_core.py
  tests/test_transformations.py
  weldx/asdf/utils.py
  weldx/core.py
  weldx/transformations.py
  weldx/utility.py
  weldx/welding/groove/iso_9692_1.py
Labels: no-changelog-entry-needed

#199 Add geometry distance example
  CHANGELOG.md
  doc/tutorials.rst
  tests/asdf_tests/test_asdf_aws_schema.py
  tutorials/experiment_design_01.ipynb
  tutorials/measurement_example.ipynb
  tutorials/welding_example_02_weaving.ipynb
  weldx/asdf/__init__.py
  weldx/geometry.py
  weldx/utility.py
Labels: tutorials
