Repository BAMWelDX/weldx, pull requests merged in 2021-08, with the labels that each got.

#457 use updated sphinx version, unpin jinja2
  doc/conf.py
  doc/rtd_environment.yml
Labels: CI, documentation, no-changelog-entry-needed

#458 Nitpick ignore cleanup
  doc/nitpick_ignore
  weldx/transformations/cs_manager.py
  weldx/visualization/k3d_impl.py
  weldx/visualization/matplotlib_impl.py
Labels: no-changelog-entry-needed

#456 [asdf] Do not copy array data
  weldx/asdf/tags/weldx/core/common_types.py
  weldx/asdf/tags/weldx/core/data_array.py
Labels: no-changelog-entry-needed, xarray

#462 update deprecated mpl plot calls
  weldx/geometry.py
Labels: no-changelog-entry-needed, visualization

#461 remove `wx_tag` validator
  CHANGELOG.md
  doc/standard/validators.rst
  weldx/asdf/validators.py
  weldx/tests/asdf_tests/test_asdf_validators.py
  weldx/transformations/local_cs.py
Labels: ASDF, deprecation, validation

#463 add asdf `time/time` schema
  CHANGELOG.md
  weldx/asdf/schemas/weldx.bam.de/weldx/time/time-1.0.0.yaml
  weldx/asdf/schemas/weldx.bam.de/weldx/time/timedelta-1.0.0.yaml
  weldx/asdf/schemas/weldx.bam.de/weldx/time/timestamp-1.0.0.yaml
  weldx/asdf/tags/weldx/time/__init__.py
  weldx/asdf/tags/weldx/time/datetimeindex.py
  weldx/asdf/tags/weldx/time/time.py
  weldx/asdf/tags/weldx/time/timedelta.py
  weldx/asdf/tags/weldx/time/timedeltaindex.py
  weldx/asdf/tags/weldx/time/timestamp.py
  weldx/tests/asdf_tests/test_asdf_time.py
Labels: ASDF, core

#465 use glob pattern to include top level schemas in docs
  doc/schemas/core.rst
  doc/schemas/datamodels.rst
  doc/schemas/equipment.rst
  doc/schemas/groove.rst
  doc/schemas/measurement.rst
  doc/schemas/time.rst
Labels: documentation, no-changelog-entry-needed

#466 update gh black action
  .github/workflows/static_analysis.yml
Labels: CI, no-changelog-entry-needed

#459 WelDXfile compression/show_header fixes
  CHANGELOG.md
  setup.cfg
  weldx/asdf/file.py
  weldx/asdf/tags/weldx/core/data_array.py
  weldx/core.py
  weldx/tests/asdf_tests/test_weldx_file.py
  weldx/util.py
Labels: file

#435 Add mypy
  .github/workflows/static_analysis.yml
  .typo-ci.yml
  CHANGELOG.md
  setup.cfg
  weldx/config.py
  weldx/core.py
  weldx/geometry.py
  weldx/measurement.py
  weldx/time.py
  weldx/transformations/cs_manager.py
  weldx/transformations/local_cs.py
  weldx/util.py
  weldx/visualization/colors.py
  weldx/visualization/k3d_impl.py
  weldx/visualization/matplotlib_impl.py
  weldx/welding/groove/iso_9692_1.py
Labels: CI

#450 Install guide
  .typo-ci.yml
  CHANGELOG.md
  doc/index.rst
  doc/install.rst
Labels: documentation

#470 replaced attrdict with custom impl.
  CHANGELOG.md
  setup.cfg
  weldx/asdf/file.py
Labels: file

#473 Fix warnings
  .deepsource.toml
  .typo-ci.yml
  setup.cfg
  weldx/asdf/file.py
  weldx/tests/asdf_tests/test_weldx_file.py
  weldx/transformations/local_cs.py
  weldx/util.py
  weldx/welding/groove/iso_9692_1.py
  weldx/welding/util.py
Labels: no-changelog-entry-needed

#468 Complete Time todos
  weldx/core.py
  weldx/tests/test_time.py
  weldx/tests/test_transformations.py
  weldx/time.py
  weldx/transformations/cs_manager.py
  weldx/transformations/local_cs.py
  weldx/transformations/types.py
  weldx/types.py
  weldx/util.py
Labels: no-changelog-entry-needed

#477 fix unambiguous timedeltas in Time docstring
  weldx/time.py
Labels: no-changelog-entry-needed

#478 Remove obsolete type hint
  weldx/transformations/local_cs.py
Labels: no-changelog-entry-needed, refactor

#476 csm time interpolation range
  CHANGELOG.md
  weldx/tests/test_transformations.py
  weldx/transformations/cs_manager.py
  weldx/transformations/local_cs.py
Labels: transformations

#484 Update gh actions
  .github/workflows/build.yml
  .github/workflows/docs.yml
  .github/workflows/pytest.yml
  .github/workflows/pytest_asdf.yml
  .github/workflows/static_analysis.yml
Labels: no-changelog-entry-needed

#485 Fix warnings
  devtools/conda.recipe/meta.yaml
  setup.cfg
  weldx/tests/test_transformations.py
  weldx/transformations/local_cs.py
Labels: no-changelog-entry-needed

#488 Separate transformation tests
  weldx/tests/test_transformations.py
  weldx/tests/transformations/__init__.py
  weldx/tests/transformations/_util.py
  weldx/tests/transformations/test_cs_manager.py
  weldx/tests/transformations/test_local_cs.py
  weldx/tests/transformations/test_util.py
Labels: tests, transformations, no-changelog-entry-needed

#489 Update weldx accessor
  CHANGELOG.md
  weldx/tests/transformations/test_local_cs.py
  weldx/util.py
Labels: refactor

#469 Dummy inline arrays in asdf.util and weldxfile
  .github/workflows/pytest.yml
  CHANGELOG.md
  conftest.py
  weldx/asdf/file.py
  weldx/asdf/util.py
  weldx/tests/asdf_tests/test_asdf_util.py
  weldx/tests/asdf_tests/test_weldx_file.py
  weldx/util.py
Labels: ASDF, file

#490 Refactor utility module
  CHANGELOG.md
  devtools/scripts/clean_notebooks.py
  weldx/asdf/file.py
  weldx/asdf/util.py
  weldx/geometry.py
  weldx/tests/_helpers.py
  weldx/tests/asdf_tests/test_asdf_util.py
  weldx/tests/test_geometry.py
  weldx/tests/test_utility.py
  weldx/tests/transformations/test_cs_manager.py
  weldx/tests/transformations/test_local_cs.py
  weldx/tests/transformations/test_util.py
  weldx/util/__init__.py
  weldx/util/util.py
  weldx/util/xarray.py
Labels: refactor

#486 Refactor interpolation
  CHANGELOG.md
  tutorials/measurement_example.ipynb
  weldx/asdf/extension.py
  weldx/asdf/file.py
  weldx/asdf/validators.py
  weldx/tags/core/transformations/local_coordinate_system.py
  weldx/tests/transformations/test_cs_manager.py
  weldx/tests/transformations/test_local_cs.py
  weldx/transformations/cs_manager.py
  weldx/transformations/local_cs.py
  weldx/util/util.py
  weldx/util/xarray.py
  weldx/visualization/matplotlib_impl.py
Labels: transformations, refactor

#494 Fix data handling during merging and unmerging of CSM instances
  CHANGELOG.md
  weldx/tags/core/transformations/coordinate_system_hierarchy.py
  weldx/tests/test_utility.py
  weldx/tests/transformations/test_cs_manager.py
  weldx/transformations/cs_manager.py
  weldx/util/util.py
Labels: transformations

#500 apply pyupgrade
  devtools/scripts/pyupgrad_run.py
  weldx/asdf/file.py
  weldx/asdf/types.py
  weldx/core.py
  weldx/geometry.py
  weldx/measurement.py
  weldx/transformations/cs_manager.py
  weldx/transformations/local_cs.py
  weldx/util/util.py
  weldx/visualization/colors.py
Labels: no-changelog-entry-needed
