Repository BAMWelDX/weldx, pull requests merged in 2021-07, with the labels that each got.

#389 pandas v1.3 & pytest warnings
  weldx/asdf/tags/weldx/aws/process/arc_welding_process.py
  weldx/tests/asdf_tests/test_asdf_aws_schema.py
  weldx/tests/test_utility.py
  weldx/transformations/local_cs.py
  weldx/util.py
Labels: no-changelog-entry-needed

#386 fixes #385
  weldx/asdf/util.py
Labels: no-changelog-entry-needed

#390 Update variable schema with attrs field
  weldx/asdf/schemas/weldx.bam.de/weldx/core/variable-1.0.0.yaml
  weldx/asdf/tags/weldx/core/common_types.py
  weldx/tests/asdf_tests/test_asdf_base_types.py
Labels: ASDF, no-changelog-entry-needed

#394 Add output_signal property to MeasurementChain
  CHANGELOG.md
  weldx/measurement.py
  weldx/tests/test_measurement.py
Labels: core, feature, measurements

#399 cleanup asdf validation tests
  CHANGELOG.md
  weldx/__init__.py
  weldx/asdf/tags/weldx/debug/test_shape_validator.py
  weldx/asdf/tags/weldx/debug/test_unit_validator.py
  weldx/asdf/util.py
  weldx/asdf/validators.py
  weldx/tests/asdf_tests/test_asdf_validators.py
Labels: validation

#401 tutorial import cleanup
  tutorials/welding_example_01_basics.ipynb
  tutorials/welding_example_02_weaving.ipynb
  weldx/__init__.py
  weldx/welding/groove/iso_9692_1.py
Labels: no-changelog-entry-needed

#402 allow str quantities for MathExpr
  CHANGELOG.md
  tutorials/timeseries_01.ipynb
  weldx/core.py
  weldx/util.py
  weldx/welding/util.py
Labels: units

#366 Support TimeSeries as possible input to LCS.__init__
  CHANGELOG.md
  tutorials/welding_example_02_weaving.ipynb
  tutorials/weldxfile.ipynb
  weldx/asdf/schemas/weldx.bam.de/weldx/core/transformations/local_coordinate_system-1.0.0.yaml
  weldx/asdf/tags/weldx/core/transformations/local_coordinate_system.py
  weldx/asdf/validators.py
  weldx/core.py
  weldx/tests/asdf_tests/test_asdf_core.py
  weldx/tests/test_transformations.py
  weldx/transformations/cs_manager.py
  weldx/transformations/local_cs.py
  weldx/transformations/util.py
Labels: transformations

#412 [WeldxFile] resolve custom_schema within weldx package.
  CHANGELOG.md
  weldx/asdf/file.py
  weldx/tests/asdf_tests/test_weldx_file.py
Labels: file

#211 Quality standards
  CHANGELOG.md
  doc/standard.rst
  doc/tutorials.rst
  setup.cfg
  tutorials/measurement_example.ipynb
  tutorials/quality_standards.ipynb
  weldx/__init__.py
  weldx/asdf/file.py
  weldx/config.py
  weldx/measurement.py
  weldx/tests/data/quality_standard/resources/test_organization/manifests/test_standard-1.0.0.yaml
  weldx/tests/data/quality_standard/resources/test_organization/schemas/alternative_measurement_equipment_schema-1.0.0.yaml
  weldx/tests/test_config.py
  weldx/types.py
Labels: ASDF, quality-standards

#410 Math expr param tag
  .github/workflows/pytest_asdf.yml
  CHANGELOG.md
  weldx/asdf/schemas/weldx.bam.de/weldx/core/mathematical_expression-1.0.0.yaml
  weldx/asdf/validators.py
Labels: ASDF, validation

#405 add test path to pytest config
  .github/workflows/pytest_asdf.yml
  setup.cfg
Labels: no-changelog-entry-needed, tests

#418 Remove appveyor
  .appveyor.yml
  .typo-ci.yml
  README.md
Labels: CI, no-changelog-entry-needed

#415 Include markdown readme in sphinx index
  README.md
  doc/changelog_link.rst
  doc/conf.py
  doc/index.rst
  doc/rtd_environment.yml
  weldx/welding/__init__.py
Labels: documentation, no-changelog-entry-needed

#416 support string units in get_groove
  CHANGELOG.md
  tutorials/groove_types_01.ipynb
  weldx/welding/groove/iso_9692_1.py
Labels: units

#419 v0.4.0
  .codacy.yml
  CHANGELOG.md
  README.md
Labels: no-changelog-entry-needed, release

#414 Closed mesh generation
  CHANGELOG.md
  weldx/geometry.py
  weldx/tests/test_geometry.py
Labels: visualization

#420 Timeseries plot function
  CHANGELOG.md
  tutorials/measurement_chain.ipynb
  tutorials/timeseries_01.ipynb
  weldx/core.py
  weldx/measurement.py
Labels: core, visualization

#429 388 timeseries init
  CHANGELOG.md
  weldx/core.py
  weldx/tests/test_core.py
Labels: core, xarray

#430 Sort csm subsystem lists
  CHANGELOG.md
  weldx/asdf/tags/weldx/core/transformations/coordinate_system_hierarchy.py
  weldx/asdf/util.py
  weldx/tests/asdf_tests/test_asdf_util.py
Labels: ASDF

#434 Update changelog action
  .github/workflows/changelog.yml
Labels: no-changelog-entry-needed

#432 v0.4.1
  CHANGELOG.md
Labels: no-changelog-entry-needed, release

#438 Update changelog
  CHANGELOG.md
Labels: no-changelog-entry-needed

#439 move util functions to welding module
  CHANGELOG.md
  tutorials/experiment_design_01.ipynb
  tutorials/measurement_example.ipynb
  tutorials/welding_example_02_weaving.ipynb
  weldx/__init__.py
  weldx/asdf/cli/welding_schema.py
  weldx/asdf/file.py
  weldx/tests/asdf_tests/test_weldx_file.py
  weldx/util.py
  weldx/welding/util.py
Labels: refactor

#442 add "units" and "dimensionality" options to `xr_check_coords`
  CHANGELOG.md
  weldx/tests/test_utility.py
  weldx/util.py
Labels: units, xarray

#444 define `Q_` directly in constants module
  weldx/__init__.py
  weldx/asdf/tags/weldx/core/common_types.py
  weldx/asdf/tags/weldx/core/time_series.py
  weldx/asdf/tags/weldx/core/transformations/rotation.py
  weldx/asdf/tags/weldx/unit/pint_quantity.py
  weldx/asdf/validators.py
  weldx/constants.py
  weldx/core.py
  weldx/measurement.py
  weldx/tests/asdf_tests/test_asdf_aws_schema.py
  weldx/tests/asdf_tests/test_asdf_core.py
  weldx/tests/asdf_tests/test_asdf_groove.py
  weldx/tests/test_core.py
  weldx/tests/test_utility.py
  weldx/tests/test_welding_util.py
  weldx/util.py
  weldx/welding/groove/iso_9692_1.py
Labels: no-changelog-entry-needed, refactor

#433 Time class
  CHANGELOG.md
  doc/api.rst
  doc/nitpick_ignore
  weldx/__init__.py
  weldx/core.py
  weldx/tests/test_time.py
  weldx/tests/test_utility.py
  weldx/time.py
  weldx/transformations/local_cs.py
  weldx/types.py
  weldx/util.py
Labels: core, feature

#452 Markdown to rst
  doc/conf.py
  doc/legal-notice.md
  doc/legal-notice.rst
  doc/shape-validation.md
  doc/standard.rst
  doc/standard/shape-validation.rst
  doc/standard/unit-validation.rst
  doc/standard/validators.rst
  doc/standard/welding-processes.rst
  doc/unit-validation.md
  doc/validators.md
  doc/welding-processes.md
Labels: documentation, no-changelog-entry-needed

#449 [csm/k3d-viz] downcast coordinates to float32
  weldx/visualization/k3d_impl.py
Labels: no-changelog-entry-needed
