Repository BAMWelDX/weldx, pull requests merged in 2021-06, with the labels that each got.

#372 update WelDX notation
  README.md
  doc/index.rst
  tutorials/transformations_01_coordinate_systems.ipynb
  tutorials/weldxfile.ipynb
  weldx/__init__.py
  weldx/util.py
Labels: no-changelog-entry-needed

#375 Fix unintentional push to master
  weldx/transformations/local_cs.py
Labels: no-changelog-entry-needed

#363 Add step interpolation to `xr_interp_like`
  CHANGELOG.md
  weldx/tests/test_utility.py
  weldx/util.py
Labels: xarray

#373 use wildcard in tag references
  CHANGELOG.md
  doc/nitpick_ignore
  doc/shape-validation.md
  doc/tutorials/.gitignore
  doc/unit-validation.md
  weldx/asdf/schemas/weldx.bam.de/weldx/aws/design/base_metal-1.0.0.yaml
  weldx/asdf/schemas/weldx.bam.de/weldx/aws/design/joint_penetration-1.0.0.yaml
  weldx/asdf/schemas/weldx.bam.de/weldx/aws/design/weld_details-1.0.0.yaml
  weldx/asdf/schemas/weldx.bam.de/weldx/aws/process/gas_component-1.0.0.yaml
  weldx/asdf/schemas/weldx.bam.de/weldx/aws/process/shielding_gas_for_procedure-1.0.0.yaml
  weldx/asdf/schemas/weldx.bam.de/weldx/core/file-1.0.0.yaml
  weldx/asdf/schemas/weldx.bam.de/weldx/core/geometry/spatial_data-1.0.0.yaml
  weldx/asdf/schemas/weldx.bam.de/weldx/core/time_series-1.0.0.yaml
  weldx/asdf/schemas/weldx.bam.de/weldx/core/transformations/rotation-1.0.0.yaml
  weldx/asdf/schemas/weldx.bam.de/weldx/core/variable-1.0.0.yaml
  weldx/asdf/schemas/weldx.bam.de/weldx/datamodels/single_pass_weld-1.0.0.schema.yaml
  weldx/asdf/schemas/weldx.bam.de/weldx/debug/test_shape_validator-1.0.0.yaml
  weldx/asdf/schemas/weldx.bam.de/weldx/debug/test_unit_validator-1.0.0.yaml
  weldx/asdf/schemas/weldx.bam.de/weldx/groove/terms-1.0.0.yaml
  weldx/asdf/schemas/weldx.bam.de/weldx/measurement/error-1.0.0.yaml
  weldx/asdf/schemas/weldx.bam.de/weldx/time/datetimeindex-1.0.0.yaml
  weldx/asdf/schemas/weldx.bam.de/weldx/time/timedeltaindex-1.0.0.yaml
Labels: ASDF

#377 Compare nested check keys
  CHANGELOG.md
  weldx/tests/test_utility.py
  weldx/util.py
Labels: bug, core, tests

#378 add dataclass_nested_eq decorator
  CHANGELOG.md
  weldx/geometry.py
  weldx/util.py
Labels: core

#379 update markdown formatting in weldxfile.ipynb
  tutorials/weldxfile.ipynb
Labels: documentation, no-changelog-entry-needed

#364 Add spatial_data to csm serialization
  CHANGELOG.md
  README.md
  weldx/asdf/schemas/weldx.bam.de/weldx/core/transformations/coordinate_system_hierarchy-1.0.0.yaml
  weldx/asdf/tags/weldx/core/geometry/spatial_data.py
  weldx/asdf/tags/weldx/core/transformations/coordinate_system_hierarchy.py
  weldx/tests/asdf_tests/test_asdf_core.py
  weldx/tests/test_geometry.py
  weldx/transformations/cs_manager.py
Labels: ASDF, transformations

#380 Simplify dataclass serialization
  CHANGELOG.md
  weldx/asdf/tags/weldx/aws/design/base_metal.py
  weldx/asdf/tags/weldx/aws/design/connection.py
  weldx/asdf/tags/weldx/aws/design/joint_penetration.py
  weldx/asdf/tags/weldx/aws/design/sub_assembly.py
  weldx/asdf/tags/weldx/aws/design/weld_details.py
  weldx/asdf/tags/weldx/aws/design/weldment.py
  weldx/asdf/tags/weldx/aws/design/workpiece.py
  weldx/asdf/tags/weldx/aws/process/arc_welding_process.py
  weldx/asdf/tags/weldx/aws/process/gas_component.py
  weldx/asdf/tags/weldx/aws/process/shielding_gas_for_procedure.py
  weldx/asdf/tags/weldx/aws/process/shielding_gas_type.py
  weldx/asdf/tags/weldx/core/common_types.py
  weldx/asdf/tags/weldx/core/geometry/spatial_data.py
  weldx/asdf/tags/weldx/equipment/measurement_equipment.py
  weldx/asdf/tags/weldx/measurement/error.py
  weldx/asdf/tags/weldx/measurement/measurement.py
  weldx/asdf/tags/weldx/measurement/signal.py
  weldx/asdf/tags/weldx/measurement/signal_transformation.py
  weldx/asdf/tags/weldx/measurement/source.py
  weldx/asdf/util.py
Labels: ASDF

#381 Fix warnings from tests
  weldx/asdf/tags/weldx/core/common_types.py
  weldx/tests/asdf_tests/test_asdf_aws_schema.py
  weldx/tests/asdf_tests/test_asdf_core.py
  weldx/tests/asdf_tests/test_asdf_gmaw_process.py
  weldx/tests/asdf_tests/test_asdf_groove.py
  weldx/tests/asdf_tests/test_asdf_measurement.py
  weldx/tests/asdf_tests/test_asdf_types.py
  weldx/tests/asdf_tests/test_asdf_validators.py
  weldx/tests/test_visualization.py
  weldx/util.py
Labels: no-changelog-entry-needed

#353 346 TimeSeries interp_time
  CHANGELOG.md
  tutorials/timeseries_01.ipynb
  tutorials/welding_example_02_weaving.ipynb
  weldx/core.py
  weldx/tests/test_core.py
  weldx/util.py
Labels: core
