Repository BAMWelDX/weldx, pull requests merged in 2021-09, with the labels that each got.

#506 pin k3d
  setup.cfg
Labels: no-changelog-entry-needed

#504 WeldxFile copy interface
  CHANGELOG.md
  weldx/asdf/file.py
  weldx/tests/asdf_tests/test_weldx_file.py
Labels: file

#507 Use micromamba in Github workflows
  .github/workflows/build.yml
  .github/workflows/docs.yml
Labels: no-changelog-entry-needed

#511 fix k3d version
  setup.cfg
Labels: no-changelog-entry-needed

#514 support legacy tag in process schema
  .github/pull_request_template.md
  weldx/asdf/file.py
  weldx/schemas/weldx.bam.de/weldx/debug/test_property_tag-1.0.0.yaml
  weldx/schemas/weldx.bam.de/weldx/process/terms-1.0.0.yaml
Labels: ASDF, no-changelog-entry-needed

#515 set ipykernel version
  .github/workflows/changelog.yml
  .github/workflows/pytest.yml
  .github/workflows/pytest_asdf.yml
  setup.cfg
Labels: no-changelog-entry-needed

#517 ignore dataset ref
  doc/nitpick_ignore
Labels: no-changelog-entry-needed

#501 compare sets in compare_nested
  weldx/tests/test_utility.py
  weldx/util/util.py
Labels: no-changelog-entry-needed

#497 CSM serialization
  CHANGELOG.md
  devtools/scripts/update_manifest.py
  weldx/asdf/extension.py
  weldx/manifests/weldx-1.0.0.yaml
  weldx/schemas/weldx.bam.de/weldx/core/transformations/coordinate_system_hierarchy-1.0.0.yaml
  weldx/schemas/weldx.bam.de/weldx/core/transformations/coordinate_system_hierarchy_legacy-1.0.0.yaml
  weldx/schemas/weldx.bam.de/weldx/core/transformations/coordinate_system_hierarchy_subsystem-1.0.0.yaml
  weldx/schemas/weldx.bam.de/weldx/core/transformations/coordinate_transformation-1.0.0.yaml
  weldx/schemas/weldx.bam.de/weldx/datamodels/single_pass_weld-1.0.0.yaml
  weldx/tags/core/transformations/__init__.py
  weldx/tags/core/transformations/_legacy/__init__.py
  weldx/tags/core/transformations/_legacy/coordinate_system_hierarchy.py
  weldx/tags/core/transformations/coordinate_system_hierarchy.py
  weldx/tests/transformations/test_cs_manager.py
  weldx/transformations/cs_manager.py
Labels: ASDF, transformations

#437 add user API section
  CHANGELOG.md
  devtools/doc/Makefile
  doc/api.rst
  doc/conf.py
  doc/index.rst
  doc/nitpick_ignore
  doc/rtd_environment.yml
  doc/tutorials.rst
  weldx/__init__.py
  weldx/asdf/file.py
  weldx/constants.py
  weldx/geometry.py
  weldx/measurement.py
  weldx/tags/unit/pint_quantity.py
  weldx/transformations/__init__.py
  weldx/transformations/local_cs.py
  weldx/welding/processes.py
  weldx/welding/util.py
Labels: documentation

#522 support tagged string, add unit schema
  CHANGELOG.md
  weldx/asdf/types.py
  weldx/constants.py
  weldx/manifests/weldx-1.0.0.yaml
  weldx/schemas/weldx.bam.de/weldx/aws/design/base_metal-1.0.0.yaml
  weldx/schemas/weldx.bam.de/weldx/aws/design/joint_penetration-1.0.0.yaml
  weldx/schemas/weldx.bam.de/weldx/aws/design/weld_details-1.0.0.yaml
  weldx/schemas/weldx.bam.de/weldx/aws/process/gas_component-1.0.0.yaml
  weldx/schemas/weldx.bam.de/weldx/aws/process/shielding_gas_for_procedure-1.0.0.yaml
  weldx/schemas/weldx.bam.de/weldx/core/graph/di_node-1.0.0.yaml
  weldx/schemas/weldx.bam.de/weldx/core/mathematical_expression-1.0.0.yaml
  weldx/schemas/weldx.bam.de/weldx/core/transformations/rotation-1.0.0.yaml
  weldx/schemas/weldx.bam.de/weldx/datamodels/single_pass_weld-1.0.0.yaml
  weldx/schemas/weldx.bam.de/weldx/debug/test_shape_validator-1.0.0.yaml
  weldx/schemas/weldx.bam.de/weldx/debug/test_unit_validator-1.0.0.yaml
  weldx/schemas/weldx.bam.de/weldx/groove/terms-1.0.0.yaml
  weldx/schemas/weldx.bam.de/weldx/measurement/error-1.0.0.yaml
  weldx/schemas/weldx.bam.de/weldx/unit/quantity-1.0.0.yaml
  weldx/schemas/weldx.bam.de/weldx/unit/unit-1.0.0.yaml
  weldx/schemas/weldx.bam.de/weldx/uuid-1.0.0.yaml
  weldx/tags/base_types.py
  weldx/tags/unit/pint_quantity.py
Labels: ASDF, units

#534 [WeldxFile] added examples and link tutorial
  weldx/asdf/file.py
Labels: documentation, no-changelog-entry-needed, file

#538 add pre-commit CI config (disable autofix for PRs)
  .github/workflows/static_analysis.yml
  .pre-commit-config.yaml
  README.md
Labels: CI, no-changelog-entry-needed

#525 Remove test case interdependency
  .github/workflows/pytest.yml
  weldx/tests/transformations/test_cs_manager.py
Labels: tests, no-changelog-entry-needed

#537 Update wx shape syntax
  CHANGELOG.md
  weldx/asdf/validators.py
Labels: validation

#545 add black and isort hooks for notebooks
  .pre-commit-config.yaml
  tutorials/GMAW_process.ipynb
  tutorials/custom_metadata.ipynb
  tutorials/experiment_design_01.ipynb
  tutorials/geometry_01_profiles.ipynb
  tutorials/geometry_02_geometry.ipynb
  tutorials/measurement_chain.ipynb
  tutorials/measurement_example.ipynb
  tutorials/quality_standards.ipynb
  tutorials/timeseries_01.ipynb
  tutorials/transformations_01_coordinate_systems.ipynb
  tutorials/transformations_02_coordinate_system_manager.ipynb
  tutorials/welding_example_01_basics.ipynb
  tutorials/welding_example_02_weaving.ipynb
  tutorials/weldxfile.ipynb
Labels: no-changelog-entry-needed

#544 update pydocstyle match patterns
  .github/workflows/static_analysis.yml
  .pre-commit-config.yaml
  setup.cfg
  weldx/transformations/cs_manager.py
Labels: CI, no-changelog-entry-needed

#548 update units to short notation in examples
  weldx/schemas/weldx.bam.de/weldx/aws/process/gas_component-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/aws/process/shielding_gas_for_procedure-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/aws/process/shielding_gas_type-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/core/mathematical_expression-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/core/time_series-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/core/transformations/rotation-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/datamodels/single_pass_weld-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/equipment/measurement_equipment-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/groove/iso_9692_1_2013_12/DHUGroove-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/groove/iso_9692_1_2013_12/DHVGroove-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/groove/iso_9692_1_2013_12/DUGroove-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/groove/iso_9692_1_2013_12/DVGroove-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/groove/iso_9692_1_2013_12/FFGroove-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/groove/iso_9692_1_2013_12/HUGroove-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/groove/iso_9692_1_2013_12/HVGroove-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/groove/iso_9692_1_2013_12/IGroove-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/groove/iso_9692_1_2013_12/UGroove-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/groove/iso_9692_1_2013_12/UVGroove-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/groove/iso_9692_1_2013_12/VGroove-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/groove/iso_9692_1_2013_12/VVGroove-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/measurement/error-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/measurement/measurement_chain-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/measurement/signal_transformation-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/measurement/source-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/unit/quantity-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/unit/unit-0.1.0.yaml
Labels: ASDF, no-changelog-entry-needed, units

#503 delegate Time function calls to pandas.Index
  CHANGELOG.md
  tutorials/welding_example_02_weaving.ipynb
  weldx/__init__.py
  weldx/tests/test_core.py
  weldx/tests/test_time.py
  weldx/tests/test_utility.py
  weldx/time.py
  weldx/util/util.py
Labels: core

#551 units refactor
  CHANGELOG.md
  tutorials/measurement_chain.ipynb
  tutorials/measurement_example.ipynb
  tutorials/timeseries_01.ipynb
  weldx/asdf/cli/welding_schema.py
  weldx/asdf/validators.py
  weldx/constants.py
  weldx/manifests/weldx-0.1.0.yaml
  weldx/measurement.py
  weldx/schemas/weldx.bam.de/weldx/aws/process/gas_component-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/aws/process/shielding_gas_for_procedure-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/aws/process/shielding_gas_type-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/core/mathematical_expression-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/core/time_series-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/core/transformations/rotation-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/core/variable-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/datamodels/single_pass_weld-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/equipment/measurement_equipment-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/groove/iso_9692_1_2013_12/DHUGroove-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/groove/iso_9692_1_2013_12/DHVGroove-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/groove/iso_9692_1_2013_12/DUGroove-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/groove/iso_9692_1_2013_12/DVGroove-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/groove/iso_9692_1_2013_12/FFGroove-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/groove/iso_9692_1_2013_12/HUGroove-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/groove/iso_9692_1_2013_12/HVGroove-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/groove/iso_9692_1_2013_12/IGroove-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/groove/iso_9692_1_2013_12/UGroove-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/groove/iso_9692_1_2013_12/UVGroove-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/groove/iso_9692_1_2013_12/VGroove-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/groove/iso_9692_1_2013_12/VVGroove-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/measurement/error-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/measurement/measurement_chain-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/measurement/signal-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/measurement/signal_transformation-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/measurement/source-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/process/GMAW-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/unit/quantity-0.1.0.yaml
  weldx/tags/core/common_types.py
  weldx/tags/core/time_series.py
  weldx/tags/core/transformations/_legacy/coordinate_system_hierarchy.py
  weldx/tags/measurement/signal.py
  weldx/tags/unit/pint_quantity.py
  weldx/tests/asdf_tests/test_asdf_measurement.py
  weldx/tests/test_measurement.py
Labels: ASDF, units, refactor

#541 use tagged string schemas
  CHANGELOG.md
  weldx/schemas/weldx.bam.de/weldx/core/file-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/core/transformations/local_coordinate_system-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/datamodels/single_pass_weld-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/process/GMAW-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/time/datetimeindex-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/time/time-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/time/timedelta-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/time/timedeltaindex-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/time/timestamp-0.1.0.yaml
  weldx/tags/time/datetimeindex.py
  weldx/tags/time/timedelta.py
  weldx/tags/time/timedeltaindex.py
  weldx/tags/time/timestamp.py
  weldx/tests/asdf_tests/test_asdf_types.py
Labels: ASDF

#536 Export geometry as CAD file
  CHANGELOG.md
  weldx/geometry.py
  weldx/tests/test_geometry.py
Labels: feature, geometry

#540 Doc fixes2
  doc/conf.py
  weldx/__init__.py
  weldx/constants.py
  weldx/time.py
Labels: documentation, no-changelog-entry-needed

#552 convert markdown files to rst
  .deepsource.toml
  .github/pull_request_template.md
  CHANGELOG.md
  CHANGELOG.rst
  README.md
  README.rst
  doc/changelog_link.rst
  doc/conf.py
  doc/index.rst
  doc/install.rst
  weldx/__init__.py
  weldx/asdf/file.py
  weldx/transformations/__init__.py
  weldx/util/__init__.py
  weldx/util/util.py
  weldx/util/xarray.py
Labels: no-changelog-entry-needed

#562 [WeldxFile] update signature matches parent
  weldx/asdf/file.py
Labels: no-changelog-entry-needed, file

#566 update package metadata
  setup.cfg
Labels: no-changelog-entry-needed

#569 set boa>=0.6 for local build
  devtools/conda.recipe/build_env.yml
Labels: CI, no-changelog-entry-needed

#565 add `Δ°` pint preprocessor
  CHANGELOG.rst
  weldx/asdf/validators.py
  weldx/constants.py
  weldx/schemas/weldx.bam.de/weldx/debug/test_unit_validator-0.1.0.yaml
  weldx/tags/debug/test_unit_validator.py
  weldx/tests/test_core.py
Labels: units

#561 update code to use units
  weldx/geometry.py
  weldx/measurement.py
  weldx/tests/test_core.py
  weldx/transformations/rotation.py
  weldx/util/xarray.py
  weldx/welding/groove/iso_9692_1.py
Labels: no-changelog-entry-needed, units

#570 Create RELEASE.md
  RELEASE.md
Labels: documentation, no-changelog-entry-needed

#571 update wx_shape validator optional syntax
  CHANGELOG.rst
  doc/standard/shape-validation.rst
  weldx/asdf/util.py
  weldx/asdf/validators.py
  weldx/schemas/weldx.bam.de/weldx/core/transformations/local_coordinate_system-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/debug/test_shape_validator-0.1.0.yaml
  weldx/tests/asdf_tests/test_asdf_validators.py
Labels: ASDF, validation
