Repository BAMWelDX/weldx, pull requests merged in 2021-11, with the labels that each got.

#622 handle SpatialData dimensions
  CHANGELOG.rst
  weldx/geometry.py
  weldx/visualization/k3d_impl.py
Labels: geometry

#621 Add xarray support to `MathematicalExpression`
  CHANGELOG.rst
  tutorials/experiment_design_01.ipynb
  tutorials/timeseries_01.ipynb
  tutorials/welding_example_02_weaving.ipynb
  weldx/core.py
  weldx/measurement.py
  weldx/tags/core/mathematical_expression.py
  weldx/tests/asdf_tests/test_asdf_core.py
  weldx/tests/test_core.py
  weldx/tests/test_time.py
  weldx/tests/transformations/test_cs_manager.py
  weldx/tests/transformations/test_local_cs.py
  weldx/time.py
Labels: xarray, core

#564 Second tutorial about time dependent data
  doc/conf.py
  doc/tutorials.rst
  tutorials/01_01_introduction.ipynb
  tutorials/01_02_time_dependent_data.ipynb
  tutorials/quality_standards.ipynb
Labels: documentation

#627 add `process` as required in single_pass_weld-0.1.0.yaml
  CHANGELOG.rst
  weldx/schemas/weldx.bam.de/weldx/datamodels/single_pass_weld-0.1.0.yaml
Labels: ASDF

#628 v0.5.1
  CHANGELOG.rst
  CITATION.cff
  RELEASE.md
Labels: no-changelog-entry-needed, release

#629 fix RTD build
  .readthedocs.yml
  doc/rtd_environment.yml
Labels: documentation, no-changelog-entry-needed, dependencies

#631 enable pint 0.18 and fix sphinx build
  doc/_templates/class-template_docstring.rst
  doc/conf.py
  doc/nitpick_ignore
  setup.cfg
  weldx/__init__.py
  weldx/constants.py
Labels: no-changelog-entry-needed, dependencies

#632 update build and release workflow
  .github/workflows/build_pkg.yml
Labels: CI, no-changelog-entry-needed

#634 remove ipykernel dependency
  .github/workflows/pytest.yml
  CHANGELOG.rst
  setup.cfg
Labels: dependencies

#633 run build on 'published' instead of 'created' release events
  .github/workflows/build_pkg.yml
Labels: CI, no-changelog-entry-needed

#635 Check time coords
  CHANGELOG.rst
  weldx/geometry.py
  weldx/tags/core/transformations/local_coordinate_system.py
  weldx/tests/transformations/test_cs_manager.py
  weldx/tests/transformations/test_local_cs.py
  weldx/time.py
  weldx/transformations/cs_manager.py
  weldx/transformations/local_cs.py
  weldx/util/xarray.py
Labels: xarray

#639 [pre-commit] added clean notebook output hook
  .github/workflows/static_analysis.yml
  .pre-commit-config.yaml
  doc/conf.py
  tutorials/GMAW_process.ipynb
  tutorials/custom_metadata.ipynb
  tutorials/experiment_design_01.ipynb
  tutorials/geometry_01_profiles.ipynb
  tutorials/geometry_02_geometry.ipynb
  tutorials/groove_types_01.ipynb
  tutorials/measurement_chain.ipynb
  tutorials/measurement_example.ipynb
  tutorials/quality_standards.ipynb
  tutorials/timeseries_01.ipynb
  tutorials/transformations_01_coordinate_systems.ipynb
  tutorials/transformations_02_coordinate_system_manager.ipynb
  tutorials/welding_example_01_basics.ipynb
  tutorials/welding_example_02_weaving.ipynb
Labels: CI, no-changelog-entry-needed

#642 fix pre-commit config regex pattern
  .pre-commit-config.yaml
  tutorials/weldxfile.ipynb
  weldx/asdf/file.py
Labels: no-changelog-entry-needed

#649 add unit handling to `Trace.plot´
  weldx/geometry.py
  weldx/tests/asdf_tests/test_weldx_file.py
Labels: no-changelog-entry-needed, units, visualization

#650 Spelling
  .pre-commit-config.yaml
  tutorials/geometry_01_profiles.ipynb
  tutorials/groove_types_01.ipynb
  tutorials/measurement_chain.ipynb
  tutorials/quality_standards.ipynb
  tutorials/weldxfile.ipynb
  weldx/asdf/util.py
  weldx/schemas/weldx.bam.de/legacy/datamodels/single_pass_weld-1.0.0.schema.yaml
  weldx/schemas/weldx.bam.de/legacy/equipment/measurement_equipment-1.0.0.yaml
  weldx/schemas/weldx.bam.de/weldx/core/transformations/coordinate_system_hierarchy-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/datamodels/single_pass_weld-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/equipment/measurement_equipment-0.1.0.yaml
  weldx/tests/data/quality_standard/resources/test_organization/schemas/alternative_measurement_equipment_schema-1.0.0.yaml
  weldx/time.py
Labels: no-changelog-entry-needed

#636 use weldx-widgets k3d implementation if available
  CHANGELOG.rst
  weldx/visualization/__init__.py
Labels: visualization

#648 csm.__eq__ now generically checks all node and edge attributes
  weldx/tests/transformations/test_cs_manager.py
  weldx/transformations/cs_manager.py
Labels: transformations, no-changelog-entry-needed

#652 v0.5.2
  CHANGELOG.rst
  CITATION.cff
Labels: no-changelog-entry-needed, release

#653 update zenodo badge
  README.rst
Labels: no-changelog-entry-needed

#659 add dependabot.yml
  .github/dependabot.yml
Labels: CI, no-changelog-entry-needed, dependencies

#658 add issue and PR directives for sphinx
  .github/workflows/changelog.yml
  CHANGELOG.rst
  doc/conf.py
Labels: documentation

#518 Pint xarray
  CHANGELOG.rst
  doc/conf.py
  setup.cfg
  weldx/constants.py
  weldx/core.py
  weldx/tests/test_utility.py
  weldx/util/xarray.py
Labels: xarray, units
