Repository BAMWelDX/weldx, pull requests merged in 2021-05, with the labels that each got.

#350 minor fixes
  .github/workflows/build.yml
  MANIFEST.in
  devtools/conda.recipe/meta.yaml
  devtools/scripts/clean_notebooks.py
  scripts/__init__.py
  setup.cfg
  weldx/asdf/cli/__init__.py
  weldx/asdf/cli/welding_schema.py
  weldx/tests/asdf_tests/test_asdf_util.py
  weldx/tests/conftest.py
  weldx/util.py
Labels: CI, no-changelog-entry-needed

#351 Fix clean_notebooks
  devtools/scripts/clean_notebooks.py
Labels: no-changelog-entry-needed

#341 Add weldx file wrapper
  .github/workflows/static_analysis.yml
  CHANGELOG.md
  doc/api.rst
  setup.cfg
  tutorials/GMAW_process.ipynb
  tutorials/custom_metadata.ipynb
  tutorials/geometry_02_geometry.ipynb
  tutorials/groove_types_01.ipynb
  tutorials/measurement_example.ipynb
  tutorials/welding_example_01_basics.ipynb
  weldx/__init__.py
  weldx/asdf/file.py
  weldx/asdf/util.py
  weldx/tests/asdf_tests/test_asdf_util.py
  weldx/tests/asdf_tests/test_weldx_file.py
  weldx/tests/test_utility.py
  weldx/types.py
  weldx/util.py
Labels: ASDF, KISA, core

#218 Asdf 2.8
  CHANGELOG.md
  devtools/environment.yml
  weldx/asdf/cli/welding_schema.py
  weldx/asdf/extension.py
  weldx/asdf/file.py
  weldx/asdf/schemas/weldx.bam.de/weldx/core/variable-1.0.0.yaml
  weldx/asdf/tags/weldx/core/common_types.py
  weldx/asdf/util.py
  weldx/tests/asdf_tests/test_asdf_time.py
  weldx/tests/asdf_tests/test_weldx_file.py
Labels: ASDF

#355 Weldxfile tutorial + minor fixes
  doc/conf.py
  doc/tutorials.rst
  tutorials/.gitignore
  tutorials/weldxfile.ipynb
Labels: ASDF, documentation

#358 [rtd] fix install of packages (allow pinning)
  .readthedocs.yml
  doc/rtd_environment.yml
Labels: CI, bug, documentation, no-changelog-entry-needed

#359 describe core features/design goals in readme
  README.md
  doc/tutorials.rst
Labels: documentation, no-changelog-entry-needed
