Repository BAMWelDX/weldx, pull requests merged in 2021-04, with the labels that each got.

#331 use black 20.8b1
  .github/workflows/static_analysis.yml
Labels: no-changelog-entry-needed

#332 fix docs build failing
  doc/rtd_environment.yml
  weldx/asdf/util.py
Labels: CI, bug, documentation, no-changelog-entry-needed

#327 fix WXRotation unit prefix
  weldx/tests/asdf_tests/test_asdf_core.py
  weldx/transformations/rotation.py
Labels: bug, no-changelog-entry-needed, units

#337 Fix typo example
  .github/workflows/pytest.yml
  tutorials/welding_example_01_basics.ipynb
Labels: no-changelog-entry-needed

#329 clean notebook IDs
  scripts/clean_notebooks.py
  tutorials/GMAW_process.ipynb
  tutorials/custom_metadata.ipynb
  tutorials/geometry_01_profiles.ipynb
  tutorials/geometry_02_geometry.ipynb
  tutorials/timeseries_01.ipynb
  tutorials/transformations_01_coordinate_systems.ipynb
  tutorials/welding_example_01_basics.ipynb
  weldx/util.py
Labels: no-changelog-entry-needed

#336 [ci/appveyor] use conda-recipe for bld/test
  .appveyor.yml
  .github/workflows/build.yml
  devtools/conda.recipe/build_env.yml
  devtools/conda.recipe/meta.yaml
  devtools/environment.yml
  setup.cfg
Labels: no-changelog-entry-needed

#330 directed graph serialization
  CHANGELOG.md
  doc/schemas/core.rst
  doc/schemas/generic.rst
  doc/standard.rst
  weldx/asdf/schemas/weldx.bam.de/weldx/core/graph/di_edge-1.0.0.yaml
  weldx/asdf/schemas/weldx.bam.de/weldx/core/graph/di_graph-1.0.0.yaml
  weldx/asdf/schemas/weldx.bam.de/weldx/core/graph/di_node-1.0.0.yaml
  weldx/asdf/schemas/weldx.bam.de/weldx/uuid-1.0.0.yaml
  weldx/asdf/tags/weldx/__init__.py
  weldx/asdf/tags/weldx/base_types.py
  weldx/asdf/tags/weldx/core/__init__.py
  weldx/asdf/tags/weldx/core/common_types.py
  weldx/asdf/tags/weldx/core/graph.py
  weldx/tests/asdf_tests/test_asdf_base_types.py
  weldx/tests/asdf_tests/test_asdf_core.py
  weldx/tests/asdf_tests/test_asdf_graph.py
Labels: ASDF

#344 [tutorials] remove cd cmd prior imports
  tutorials/GMAW_process.ipynb
  tutorials/custom_metadata.ipynb
  tutorials/experiment_design_01.ipynb
  tutorials/geometry_01_profiles.ipynb
  tutorials/geometry_02_geometry.ipynb
  tutorials/groove_types_01.ipynb
  tutorials/measurement_example.ipynb
  tutorials/timeseries_01.ipynb
  tutorials/transformations_01_coordinate_systems.ipynb
  tutorials/transformations_02_coordinate_system_manager.ipynb
  tutorials/welding_example_01_basics.ipynb
  tutorials/welding_example_02_weaving.ipynb
Labels: documentation, no-changelog-entry-needed

#347 Remove Travis
  .travis.yml
Labels: CI, no-changelog-entry-needed
