Repository BAMWelDX/weldx, pull requests merged in 2022-02, with the labels that each got.

#698 [doc] fix SciPy intersphinx link
  doc/conf.py
  doc/nitpick_ignore
Labels: documentation, no-changelog-entry-needed

#700 asdf 3.0 epic
  .github/workflows/pytest.yml
  .github/workflows/pytest_asdf.yml
  setup.cfg
  tutorials/measurement_example.ipynb
  weldx/asdf/cli/welding_schema.py
  weldx/asdf/extension.py
  weldx/asdf/file.py
  weldx/asdf/util.py
  weldx/asdf/validators.py
  weldx/tags/debug/test_unit_validator.py
  weldx/tests/asdf_tests/test_asdf_validators.py
  weldx/tests/asdf_tests/test_weldx_file.py
Labels: ASDF

#701 add and run mdformat
  .pre-commit-config.yaml
  RELEASE.md
Labels: no-changelog-entry-needed

#697 split read/write schema validation
  CHANGELOG.rst
  README.rst
  weldx/asdf/file.py
  weldx/tests/asdf_tests/test_weldx_file.py
Labels: ASDF, file

#683 Check units of coordinates
  CHANGELOG.rst
  tutorials/01_03_geometry.ipynb
  tutorials/experiment_design_01.ipynb
  tutorials/geometry_01_profiles.ipynb
  tutorials/geometry_02_geometry.ipynb
  tutorials/welding_example_01_basics.ipynb
  tutorials/welding_example_02_weaving.ipynb
  weldx/constants.py
  weldx/geometry.py
  weldx/schemas/weldx.bam.de/weldx/core/transformations/local_coordinate_system-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/datamodels/single_pass_weld-0.1.0.yaml
  weldx/schemas/weldx.bam.de/weldx/debug/test_unit_validator-0.1.0.yaml
  weldx/tests/transformations/test_cs_manager.py
  weldx/tests/transformations/test_local_cs.py
  weldx/transformations/cs_manager.py
  weldx/transformations/local_cs.py
  weldx/transformations/types.py
  weldx/visualization/k3d_impl.py
  weldx/visualization/matplotlib_impl.py
Labels: transformations, units

#707 allow string in `core/variable`, default tag sorting
  CHANGELOG.rst
  weldx/manifests/weldx-0.1.1.yaml
  weldx/schemas/weldx.bam.de/weldx/core/variable-0.1.1.yaml
  weldx/tags/core/common_types.py
  weldx/tests/asdf_tests/test_asdf_core.py
Labels: ASDF, xarray

#708 Fix package build.yml
  devtools/conda.recipe/meta.yaml
Labels: no-changelog-entry-needed

#667 add multi_pass_weld-0.1.0.yaml
  CHANGELOG.rst
  weldx/schemas/weldx.bam.de/weldx/datamodels/multi_pass_weld-0.1.0.yaml
Labels: ASDF

#705 Download `single_pass_weld.wx` directly in the tutorials
  doc/conf.py
  tutorials/01_01_introduction.ipynb
  tutorials/01_02_time_dependent_data.ipynb
  tutorials/01_03_geometry.ipynb
  tutorials/util.py
Labels: documentation, no-changelog-entry-needed

#696 use Python-3.10 in docs building, testing
  .github/workflows/docs.yml
  .github/workflows/pytest.yml
  .github/workflows/pytest_asdf.yml
  CHANGELOG.rst
  setup.cfg
Labels: dependencies

#710 ignore matplotlib docs link warnings
  doc/nitpick_ignore
Labels: documentation, no-changelog-entry-needed

#699 `SpatialSeries` and `DynamicTraceSegment`
  .pre-commit-config.yaml
  CHANGELOG.rst
  tutorials/01_03_geometry.ipynb
  tutorials/welding_example_01_basics.ipynb
  weldx/__init__.py
  weldx/core.py
  weldx/geometry.py
  weldx/tests/_helpers.py
  weldx/tests/test_geometry.py
Labels: geometry, core
