Repository BAMWelDX/weldx, pull requests merged in 2022-04, with the labels that each got.

#734 Fix doctests
  weldx/geometry.py
Labels: bug, no-changelog-entry-needed

#733 set default tag sorting order
  CHANGELOG.rst
  weldx/asdf/types.py
  weldx/tags/core/data_array.py
  weldx/tags/core/dataset.py
  weldx/tags/core/file.py
  weldx/tags/core/generic_series.py
  weldx/tags/core/graph.py
  weldx/tags/core/mathematical_expression.py
  weldx/tags/core/transformations/local_coordinate_system.py
  weldx/tags/core/transformations/rotation.py
  weldx/tags/measurement/measurement_chain.py
  weldx/tags/time/datetimeindex.py
  weldx/tags/time/time.py
  weldx/tags/time/timedeltaindex.py
  weldx/tags/units/pint_quantity.py
Labels: ASDF

#739 custom `wx_unit` validation behavior
  CHANGELOG.rst
  weldx/asdf/util.py
  weldx/asdf/validators.py
  weldx/schemas/weldx.bam.de/weldx/debug/test_unit_validator-0.1.0.yaml
  weldx/tags/core/data_array.py
  weldx/tags/debug/test_unit_validator.py
  weldx/tests/asdf_tests/test_asdf_validators.py
Labels: ASDF, validation

#740 cache conda env in CI runs
  .github/workflows/build_pkg.yml
  .github/workflows/docs.yml
  doc/rtd_environment.yml
Labels: CI, no-changelog-entry-needed

#742 Update ci
  .github/workflows/build_pkg.yml
  .github/workflows/docs.yml
  .github/workflows/pytest.yml
Labels: CI, no-changelog-entry-needed
