Repository BAMWelDX/weldx, pull requests merged in 2022-05, with the labels that each got.

#750 Update changlog link
  CHANGELOG.rst
Labels: no-changelog-entry-needed

#751 Minor changes
  .github/workflows/docs.yml
  weldx/constants.py
  weldx/types.py
  weldx/welding/groove/iso_9692_1.py
Labels: no-changelog-entry-needed

#755 remove old visualization modules
  .github/workflows/docs.yml
  .github/workflows/pytest.yml
  weldx/visualization/colors.py
  weldx/visualization/types.py
Labels: no-changelog-entry-needed, refactor

#756 convert to base types for view_tree
  CHANGELOG.rst
  doc/conf.py
  weldx/asdf/util.py
Labels: ASDF

#758 convert to base types for view_tree [fix]
  weldx/asdf/util.py
Labels: no-changelog-entry-needed

#760 update zenodo badge
  README.rst
Labels: documentation, no-changelog-entry-needed

#761 set networkx<=2.8.0
  CHANGELOG.rst
  setup.cfg
Labels: dependencies

#762 v0.6.1
  CHANGELOG.rst
  CITATION.cff
  README.rst
  doc/install.rst
Labels: no-changelog-entry-needed, release

#765 [doc] fix scipy intersphinx mapping (again)
  doc/conf.py
Labels: no-changelog-entry-needed

#766 [doc] fix pattern for extlinks, use Sphinx-bundled (up2date) napoleon
  doc/conf.py
  doc/rtd_environment.yml
  weldx/asdf/file.py
Labels: no-changelog-entry-needed

#763 Revert "set networkx<=2.8.0"
  CHANGELOG.rst
  setup.cfg
Labels: no-changelog-entry-needed
