Repository BAMWelDX/weldx, pull requests merged in 2022-03, with the labels that each got.

#714 set networkx<2.7
  CHANGELOG.rst
  doc/conf.py
  setup.cfg
Labels: dependencies

#717 allow asdf 2.10
  doc/nitpick_ignore
  setup.cfg
Labels: no-changelog-entry-needed, dependencies

#721 Fix sympy error
  doc/conf.py
  weldx/geometry.py
Labels: bug, no-changelog-entry-needed

#722 allow networkx >2.7.0
  CHANGELOG.rst
  setup.cfg
Labels: dependencies

#713 Add `DynamicShapeSegment`
  CHANGELOG.rst
  weldx/__init__.py
  weldx/core.py
  weldx/geometry.py
  weldx/tests/test_geometry.py
Labels: geometry, refactor

#723 reshape point data for `meshio` file export
  CHANGELOG.rst
  weldx/geometry.py
Labels: geometry

#712 Update `GenericSeries` docstrings
  weldx/core.py
Labels: documentation, no-changelog-entry-needed

#729 fix docs build
  doc/rtd_environment.yml
Labels: documentation, no-changelog-entry-needed

#730 add git diff check
  .github/workflows/pytest_asdf.yml
  devtools/scripts/update_manifest.py
  weldx/manifests/weldx-0.1.1.yaml
Labels: no-changelog-entry-needed
