Repository BAMWelDX/weldx, pull requests merged in 2023-01, with the labels that each got.

#831 remove get_highest_tag_version from converters
  CHANGELOG.rst
  weldx/tags/core/geometry/spatial_data.py
  weldx/tags/core/time_series.py
Labels: ASDF

#824 use Ruff linter pre-commit actions
  .flake8
  .pre-commit-config.yaml
  CHANGELOG.rst
  devtools/environment.yml
  devtools/scripts/clean_notebooks.py
  pyproject.toml
  tutorials/01_03_geometry.ipynb
  tutorials/custom_metadata.ipynb
  tutorials/experiment_design_01.ipynb
  tutorials/generic_series.ipynb
  tutorials/geometry_02_geometry.ipynb
  tutorials/groove_types_01.ipynb
  tutorials/measurement_example.ipynb
  tutorials/quality_standards.ipynb
  tutorials/timeseries_01.ipynb
  tutorials/transformations_01_coordinate_systems.ipynb
  tutorials/transformations_02_coordinate_system_manager.ipynb
  tutorials/welding_example_02_weaving.ipynb
  tutorials/weldxfile.ipynb
  weldx/asdf/file.py
  weldx/asdf/util.py
  weldx/constants.py
  weldx/core/generic_series.py
  weldx/core/time_series.py
  weldx/geometry.py
  weldx/measurement.py
  weldx/tests/asdf_tests/test_asdf_core.py
  weldx/tests/asdf_tests/test_weldx_file.py
  weldx/tests/test_geometry.py
  weldx/tests/test_time.py
  weldx/tests/test_utility.py
  weldx/tests/transformations/test_cs_manager.py
  weldx/tests/transformations/test_local_cs.py
  weldx/time.py
  weldx/transformations/cs_manager.py
  weldx/transformations/local_cs.py
  weldx/transformations/rotation.py
  weldx/util/util.py
  weldx/welding/groove/iso_9692_1.py
Labels: enhancement

#834 Unpin ASDF
  CHANGELOG.rst
  pyproject.toml
Labels: ASDF, dependencies

#835 [GithubActions] Test old ASDF minor versions
  .github/workflows/pytest_asdf.yml
Labels: ASDF, no-changelog-entry-needed

#842 update ruff 233, nbqa 1.6.1
  .pre-commit-config.yaml
Labels: no-changelog-entry-needed

#843 remove macos from test ci
  .github/workflows/pytest.yml
Labels: CI, no-changelog-entry-needed

#841 add validate-pyproject
  .pre-commit-config.yaml
  pyproject.toml
Labels: CI, no-changelog-entry-needed

#727 Schema media file
  .github/workflows/build_pkg.yml
  .github/workflows/pytest.yml
  CHANGELOG.md
  pyproject.toml
  weldx/asdf/file.py
  weldx/asdf/types.py
  weldx/asdf/util.py
  weldx/manifests/weldx-0.1.1.yaml
  weldx/schemas/weldx.bam.de/weldx/core/file-0.1.1.yaml
  weldx/schemas/weldx.bam.de/weldx/core/media_file-0.1.0.yaml
  weldx/tags/core/__init__.py
  weldx/tags/core/file.py
  weldx/tags/core/media_file.py
  weldx/tests/asdf_tests/test_asdf_core.py
  weldx/tests/asdf_tests/test_media_file.py
  weldx/time.py
  weldx/util/__init__.py
  weldx/util/external_file.py
  weldx/util/media_file.py
Labels: ASDF

#847 Update mypy action
  .github/workflows/static_analysis.yml
Labels: CI, no-changelog-entry-needed
