Repository BAMWelDX/weldx, pull requests merged in 2025-04, with the labels that each got.

#971 Update README.md
  README.md
  doc/src/install.md
Labels: documentation, no-changelog-entry-needed

#959 unpin numpy, python
  .github/workflows/pytest.yml
  CHANGELOG.md
  pyproject.toml
  weldx/tests/asdf_tests/test_weldx_file.py
  weldx/tests/test_utility.py
Labels: dependencies

#974 update CITATION.cff
  .github/workflows/citation.yml
  .pre-commit-config.yaml
  CITATION.cff
Labels: no-changelog-entry-needed

#978 use render plugin from github repo
  CHANGELOG.md
  devtools/conda.recipe/meta.yaml
  doc/json_mime_render_plugin/README.md
  doc/json_mime_render_plugin/myst_nb_json_render_plugin.py
  doc/json_mime_render_plugin/pyproject.toml
  doc/rtd_environment.yml
  doc/src/tutorials/01_01_introduction.ipynb
  pyproject.toml
  weldx/asdf/file.py
Labels: documentation, CI, dependencies

#981 v0.7.1
  .codacy.yml
  .deepsource.toml
  .gitattributes
  .github/workflows/pytest_asdf.yml
  .gitignore
  CHANGELOG.md
  CITATION.cff
  pyproject.toml
  weldx/__init__.py
  weldx/asdf/file.py
Labels: release

#984 Update GH action badges in README.md
  README.md
Labels: no-changelog-entry-needed
